# Generated by Django 3.1.4 on 2020-12-23 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0003_book_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='Bookname',
        ),
    ]
